name: CI/CD for swiggy-clone

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: |
          cd ./
          npm install

      - name: Build Project
        run: |
          cd ./
          npm run build

      
  # Deploy Job
  deploy:
   
    needs: build
    
    runs-on: ubuntu-latest
    steps:
      

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SECRET_KEY }} #this is the key of the access token
          publish_dir: ./build
